### ISSUE TITLE
cuelga al cargar imágenes con nombre que tiene ñ

### ISSUE THREAD

**Issue by Diex** [Diex/barraspectorales#1]
Caused by: java.lang.RuntimeException: This file is named PIÑERO JOSE (Inferior_3).jpg not /Volumes/work/personas/ERKOM3D/images/PIN?ERO JOSE (Inferior_3).jpg. Rename the file or change your code.
    at processing.core.PApplet.createInputRaw(PApplet.java:7279)
    at processing.core.PApplet.createInput(PApplet.java:7201)
    at processing.core.PApplet.loadImageIO(PApplet.java:6037)

**Comment by Diex** [comment]
no usar archivos con nombres que contengan ñ
